### ISSUE TITLE
CUDA 10.0 always needed?

### ISSUE THREAD

**Issue by andreanans** [cianfrocco-lab/Automatic-cryoEM-preprocessing#13]
Hi,

I recently installed 0.2.1 and specified cudatoolkit=10.1.168=0 and cudnn=7.6.4=cuda10.1_0 during the conda environment installation. However, when I try to run 2dassess or micasses it looks for CUDA 10.0 in my LD_LIBRARY_PATH. It will not run unless I load CUDA 10.0 into my environment. Is there a way around this so it just uses the CUDA 10.1 specified in the conda environment? Thank you!

**Comment by yilaili** [comment]
My guess is this is due to the compatibility between cuda and tensorflow. In the setup.py it installs tensorflow 1.14.0, whose compatible cuda is 10.0. (https://www.tensorflow.org/install/source#gpu). For cuda 10.1, I think the compatible tensorflow is 2.1 or above, however the code was not tested with tensorflow 2.0 or above so I don't know there will be any issues. Hope that answers your questions and sorry for not being able to fix it!

**Comment by andreanans** [comment]
I created a fresh conda environment and now it uses the cuda 10.0 that was installed via conda. However, I had to manually install the following:  

cudatoolkit=10.0.130=0
cudnn=7.6.4=cuda10.0_0

For some reason an older version of cudnn had been installed that wasn't compatible with the latest version of 0.2.1.

Thanks for your help!
